export default {

    entities: [
        {
            "name": "Homo heidelbergensis",
            "labelFR": "Homo heidelbergensis",
            "labelEN": "Homo heidelbergensis",
            "descriptionMarkDownFR": "Ancêtre commun possible des humains modernes et des Néandertaliens.",
            "descriptionMarkDownEN": "Possible common ancestor of modern humans and Neanderthals.",
            "dateStart": -700000,
            "dateEnd": -200000,
            "availableSnapshots": [-123000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Neanderthal",
            "labelFR": "Homme de Néandertal",
            "labelEN": "Neanderthals",
            "descriptionMarkDownFR": "Espèce humaine éteinte ayant vécu en Eurasie.",
            "descriptionMarkDownEN": "Extinct species or subspecies of archaic humans who lived in Eurasia.",
            "dateStart": -400000,
            "dateEnd": -40000,
            "availableSnapshots": [-123000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Homo erectus",
            "labelFR": "Homo erectus",
            "labelEN": "Homo erectus",
            "descriptionMarkDownFR": "Hominidé ancien ayant maîtrisé le feu et quitté l'Afrique.",
            "descriptionMarkDownEN": "Early hominid that mastered fire and migrated out of Africa.",
            "dateStart": -2000000,
            "dateEnd": -110000,
            "availableSnapshots": [-123000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Austronesians",
            "labelFR": "Austronésiens",
            "labelEN": "Austronesians",
            "descriptionMarkDownFR": "Peuple de navigateurs en expansion depuis Taïwan vers le Pacifique.",
            "descriptionMarkDownEN": "Seafaring people expanding from Taiwan throughout the Pacific.",
            "dateStart": -10000,
            "dateEnd": 1000,
            "availableSnapshots": [-10000, -8000, -5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Aboriginal Tasmanians",
            "labelFR": "Aborigènes de Tasmanie",
            "labelEN": "Aboriginal Tasmanians",
            "descriptionMarkDownFR": "Peuple isolé sur l'île de Tasmanie après la montée des eaux.",
            "descriptionMarkDownEN": "People isolated on the island of Tasmania after rising sea levels.",
            "dateStart": -35000,
            "dateEnd": 1876,
            "availableSnapshots": [-10000, -8000, -5000, -4000, -3000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Jōmon",
            "labelFR": "Période Jōmon",
            "labelEN": "Jōmon period",
            "descriptionMarkDownFR": "Culture de chasseurs-cueilleurs du Japon ancien connue pour ses poteries.",
            "descriptionMarkDownEN": "Ancient Japanese hunter-gatherer culture known for its pottery.",
            "dateStart": -14000,
            "dateEnd": -300,
            "availableSnapshots": [-10000, -8000, -5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Khoisan",
            "labelFR": "Khoïsan",
            "labelEN": "Khoisan",
            "descriptionMarkDownFR": "Premiers peuples d'Afrique australe.",
            "descriptionMarkDownEN": "First peoples of Southern Africa.",
            "dateStart": -100000,
            "dateEnd": 2024,
            "availableSnapshots": [-10000, -8000, -4000, -3000, -2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Hunters-gatherers",
            "labelFR": "Chasseurs-cueilleurs",
            "labelEN": "Hunter-gatherers",
            "descriptionMarkDownFR": "Groupes nomades génériques vivant de la chasse et de la cueillette.",
            "descriptionMarkDownEN": "Generic nomadic groups living by foraging and hunting.",
            "dateStart": -200000,
            "dateEnd": -1000,
            "availableSnapshots": [-10000, -8000, -4000, -3000, -2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Okhotsk culture",
            "labelFR": "Culture d'Okhotsk",
            "labelEN": "Okhotsk culture",
            "descriptionMarkDownFR": "Culture de pêcheurs et chasseurs côtiers autour de la mer d'Okhotsk.",
            "descriptionMarkDownEN": "Coastal fishing and hunting culture around the Sea of Okhotsk.",
            "dateStart": -10000,
            "dateEnd": 1000,
            "availableSnapshots": [-10000, -8000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Aboriginal tribes",
            "labelFR": "Tribus Aborigènes",
            "labelEN": "Aboriginal tribes",
            "descriptionMarkDownFR": "Diverses tribus indigènes d'Australie continentale.",
            "descriptionMarkDownEN": "Various indigenous tribes of mainland Australia.",
            "dateStart": -50000,
            "dateEnd": 2024,
            "availableSnapshots": [-10000, -8000, -5000, -4000, -3000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Steppe Mesolithic Hunter-Foragers",
            "labelFR": "Chasseurs Mésolithiques des Steppes",
            "labelEN": "Steppe Mesolithic Hunter-Foragers",
            "descriptionMarkDownFR": "Populations nomades des steppes eurasiennes avant l'agriculture.",
            "descriptionMarkDownEN": "Nomadic populations of the Eurasian steppes before agriculture.",
            "dateStart": -12000,
            "dateEnd": -5000,
            "availableSnapshots": [-10000, -8000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "HIghland Mesolithic Hunter-Foragers",
            "labelFR": "Chasseurs Mésolithiques des Hautes Terres",
            "labelEN": "Highland Mesolithic Hunter-Foragers",
            "descriptionMarkDownFR": "Chasseurs-cueilleurs vivant dans les régions montagneuses.",
            "descriptionMarkDownEN": "Hunter-gatherers living in highland regions.",
            "dateStart": -12000,
            "dateEnd": -5000,
            "availableSnapshots": [-10000, -8000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Coastal and Woodland Mesolithic Hunter-Foragers",
            "labelFR": "Chasseurs Mésolithiques Côtiers et Forestiers",
            "labelEN": "Coastal and Woodland Mesolithic Hunter-Foragers",
            "descriptionMarkDownFR": "Populations exploitant les ressources forestières et marines.",
            "descriptionMarkDownEN": "Populations exploiting forest and marine resources.",
            "dateStart": -12000,
            "dateEnd": -5000,
            "availableSnapshots": [-10000, -8000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Bantu",
            "labelFR": "Bantous",
            "labelEN": "Bantu",
            "descriptionMarkDownFR": "Groupe ethno-linguistique majeur en expansion à travers l'Afrique.",
            "descriptionMarkDownEN": "Major ethno-linguistic group expanding across Africa.",
            "dateStart": -3000,
            "dateEnd": 2024,
            "availableSnapshots": [-8000, -5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Dakapeng culture",
            "labelFR": "Culture de Dakapeng",
            "labelEN": "Dakapeng culture",
            "descriptionMarkDownFR": "Culture néolithique ancienne d'Asie du Sud-Est.",
            "descriptionMarkDownEN": "Early Neolithic culture in Southeast Asia.",
            "dateStart": -5000,
            "dateEnd": -1000,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Kelteminar",
            "labelFR": "Kelteminar",
            "labelEN": "Kelteminar",
            "descriptionMarkDownFR": "Culture de pêcheurs néolithiques en Asie Centrale.",
            "descriptionMarkDownEN": "Neolithic fishing culture in Central Asia.",
            "dateStart": -5500,
            "dateEnd": -3500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Norte Chico",
            "labelFR": "Norte Chico (Caral)",
            "labelEN": "Norte Chico",
            "descriptionMarkDownFR": "Plus ancienne civilisation connue des Amériques (Pérou).",
            "descriptionMarkDownEN": "Oldest known civilization in the Americas (Peru).",
            "dateStart": -3500,
            "dateEnd": -1800,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Khoiasan",
            "labelFR": "Khoïsan (Typo)",
            "labelEN": "Khoiasan (Typo)",
            "descriptionMarkDownFR": "Entrée dupliquée (faute de frappe) pour Khoisan.",
            "descriptionMarkDownEN": "Duplicate entry (typo) for Khoisan.",
            "dateStart": -100000,
            "dateEnd": 2024,
            "availableSnapshots": [-5000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Hurrian Kingdoms",
            "labelFR": "Royaumes Hourrites",
            "labelEN": "Hurrian Kingdoms",
            "descriptionMarkDownFR": "Peuple du Proche-Orient ancien, précurseurs du Mitanni.",
            "descriptionMarkDownEN": "Ancient Near East people, precursors to Mitanni.",
            "dateStart": -2500,
            "dateEnd": -1000,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "KINGDOM",
            "base64Icon": ""
        },
        {
            "name": "Valdivia",
            "labelFR": "Culture Valdivia",
            "labelEN": "Valdivia Culture",
            "descriptionMarkDownFR": "Une des plus anciennes cultures néolithiques des Amériques (Équateur).",
            "descriptionMarkDownEN": "One of the oldest settled cultures in the Americas (Ecuador).",
            "dateStart": -3500,
            "dateEnd": -1500,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Ainu",
            "labelFR": "Aïnous",
            "labelEN": "Ainu",
            "descriptionMarkDownFR": "Peuple indigène du nord du Japon et de Russie.",
            "descriptionMarkDownEN": "Indigenous people of northern Japan and Russia.",
            "dateStart": -10000,
            "dateEnd": 2024,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Dravidians",
            "labelFR": "Dravidiens",
            "labelEN": "Dravidians",
            "descriptionMarkDownFR": "Locuteurs de langues dravidiennes en Asie du Sud.",
            "descriptionMarkDownEN": "Speakers of Dravidian languages in South Asia.",
            "dateStart": -4000,
            "dateEnd": 2024,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Namazga",
            "labelFR": "Namazga",
            "labelEN": "Namazga",
            "descriptionMarkDownFR": "Site urbain majeur de l'âge du bronze en Asie centrale.",
            "descriptionMarkDownEN": "Major urban site of the Bronze Age in Central Asia.",
            "dateStart": -5000,
            "dateEnd": -1500,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": " Kelteminar culture",
            "labelFR": "Culture de Kelteminar",
            "labelEN": "Kelteminar culture",
            "descriptionMarkDownFR": "Culture de Kelteminar (avec espace initial).",
            "descriptionMarkDownEN": "Kelteminar culture (with leading space).",
            "dateStart": -5500,
            "dateEnd": -3500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Naquada I",
            "labelFR": "Nagada I",
            "labelEN": "Naquada I",
            "descriptionMarkDownFR": "Culture prédynastique égyptienne (Amratien).",
            "descriptionMarkDownEN": "Egyptian Predynastic culture (Amratian).",
            "dateStart": -4400,
            "dateEnd": -3500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Ubaid",
            "labelFR": "Période d'Obeïd",
            "labelEN": "Ubaid period",
            "descriptionMarkDownFR": "Période préhistorique de la Mésopotamie.",
            "descriptionMarkDownEN": "Prehistoric period of Mesopotamia.",
            "dateStart": -6500,
            "dateEnd": -3800,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Ghassul",
            "labelFR": "Ghassulien",
            "labelEN": "Ghassulian",
            "descriptionMarkDownFR": "Culture chalcolithique du Levant sud.",
            "descriptionMarkDownEN": "Chalcolithic culture of the Southern Levant.",
            "dateStart": -4500,
            "dateEnd": -3500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Amuq D",
            "labelFR": "Amuq D",
            "labelEN": "Amuq D",
            "descriptionMarkDownFR": "Phase archéologique de la plaine d'Antioche.",
            "descriptionMarkDownEN": "Archaeological phase of the plain of Antioch.",
            "dateStart": -5000,
            "dateEnd": -4500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "La Almagra culture",
            "labelFR": "Culture de La Almagra",
            "labelEN": "La Almagra culture",
            "descriptionMarkDownFR": "Culture néolithique de la poterie rouge en Espagne.",
            "descriptionMarkDownEN": "Neolithic Red Pottery culture in Spain.",
            "dateStart": -5500,
            "dateEnd": -4500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Dimini",
            "labelFR": "Culture de Dimini",
            "labelEN": "Dimini culture",
            "descriptionMarkDownFR": "Culture néolithique tardive de Thessalie (Grèce).",
            "descriptionMarkDownEN": "Late Neolithic culture of Thessaly (Greece).",
            "dateStart": -4800,
            "dateEnd": -4500,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Cardial Ware culture",
            "labelFR": "Culture de la Céramique Cardiale",
            "labelEN": "Cardial Ware culture",
            "descriptionMarkDownFR": "Première culture néolithique d'Europe méditerranéenne.",
            "descriptionMarkDownEN": "First Neolithic culture of Mediterranean Europe.",
            "dateStart": -6000,
            "dateEnd": -5000,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Volga-Kamm",
            "labelFR": "Culture de la Volga-Kama",
            "labelEN": "Volga-Kama culture",
            "descriptionMarkDownFR": "Culture néolithique de la région de l'Oural.",
            "descriptionMarkDownEN": "Neolithic culture of the Ural region.",
            "dateStart": -5000,
            "dateEnd": -3000,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Stentinello culture",
            "labelFR": "Culture de Stentinello",
            "labelEN": "Stentinello culture",
            "descriptionMarkDownFR": "Culture néolithique de Sicile et Calabre.",
            "descriptionMarkDownEN": "Neolithic culture of Sicily and Calabria.",
            "dateStart": -5500,
            "dateEnd": -4000,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Early combware",
            "labelFR": "Céramique à peigne (Ancienne)",
            "labelEN": "Early Comb Ceramic",
            "descriptionMarkDownFR": "Culture de chasseurs-cueilleurs du nord-est de l'Europe.",
            "descriptionMarkDownEN": "Hunter-gatherer culture of Northeastern Europe.",
            "dateStart": -4200,
            "dateEnd": -2000,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Narva",
            "labelFR": "Culture de Narva",
            "labelEN": "Narva culture",
            "descriptionMarkDownFR": "Culture mésolithique/néolithique des pays baltes.",
            "descriptionMarkDownEN": "Mesolithic/Neolithic culture of the Baltic states.",
            "dateStart": -5300,
            "dateEnd": -1750,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Nemay",
            "labelFR": "Nemay (Neman)",
            "labelEN": "Nemay (Neman)",
            "descriptionMarkDownFR": "Probable référence à la culture du Niémen.",
            "descriptionMarkDownEN": "Likely refers to the Neman culture.",
            "dateStart": -7000,
            "dateEnd": -3000,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Funnel-Beaker",
            "labelFR": "Culture des Vases à Entonnoir",
            "labelEN": "Funnelbeaker culture (TRB)",
            "descriptionMarkDownFR": "Première culture agricole du nord de l'Europe.",
            "descriptionMarkDownEN": "First farming culture of Northern Europe.",
            "dateStart": -4300,
            "dateEnd": -2800,
            "availableSnapshots": [-5000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Elam",
            "labelFR": "Élam",
            "labelEN": "Elam",
            "descriptionMarkDownFR": "Ancienne civilisation située dans le sud-ouest de l'Iran.",
            "descriptionMarkDownEN": "Ancient civilization located in southwestern Iran.",
            "dateStart": -3200,
            "dateEnd": -539,
            "availableSnapshots": [-5000, -4000, -3000, -2000],
            "type": "EMPIRE",
            "base64Icon": ""
        },
        {
            "name": "city-states",
            "labelFR": "Cités-États",
            "labelEN": "City-states",
            "descriptionMarkDownFR": "Villes indépendantes (ex: Sumer, Grèce).",
            "descriptionMarkDownEN": "Independent cities (e.g., Sumer, Greece).",
            "dateStart": -4000,
            "dateEnd": -300,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "KINGDOM",
            "base64Icon": ""
        },
        {
            "name": "Ur",
            "labelFR": "Ur",
            "labelEN": "Ur",
            "descriptionMarkDownFR": "Cité-État sumérienne majeure en Mésopotamie.",
            "descriptionMarkDownEN": "Major Sumerian city-state in Mesopotamia.",
            "dateStart": -3800,
            "dateEnd": -500,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "KINGDOM",
            "base64Icon": ""
        },
        {
            "name": "Egypt",
            "labelFR": "Égypte Antique",
            "labelEN": "Ancient Egypt",
            "descriptionMarkDownFR": "Civilisation majeure le long du Nil.",
            "descriptionMarkDownEN": "Major civilization along the Nile River.",
            "dateStart": -3100,
            "dateEnd": -30,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "EMPIRE",
            "base64Icon": ""
        },
        {
            "name": "Indus valley civilization",
            "labelFR": "Civilisation de la Vallée de l'Indus",
            "labelEN": "Indus Valley Civilization",
            "descriptionMarkDownFR": "Civilisation de l'âge du bronze en Asie du Sud (Harappa).",
            "descriptionMarkDownEN": "Bronze Age civilization in South Asia (Harappan).",
            "dateStart": -3300,
            "dateEnd": -1300,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "EMPIRE",
            "base64Icon": ""
        },
        {
            "name": "Kerma",
            "labelFR": "Royaume de Kerma",
            "labelEN": "Kingdom of Kerma",
            "descriptionMarkDownFR": "Puissante civilisation nubienne (Soudan actuel).",
            "descriptionMarkDownEN": "Powerful Nubian civilization (modern Sudan).",
            "dateStart": -2500,
            "dateEnd": -1500,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "KINGDOM",
            "base64Icon": ""
        },
        {
            "name": "Minoan",
            "labelFR": "Civilisation Minoenne",
            "labelEN": "Minoan Civilization",
            "descriptionMarkDownFR": "Civilisation palatiale de la Crète.",
            "descriptionMarkDownEN": "Palatial civilization of Crete.",
            "dateStart": -3500,
            "dateEnd": -1100,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "EMPIRE",
            "base64Icon": ""
        },
        {
            "name": "Cycladic",
            "labelFR": "Civilisation des Cyclades",
            "labelEN": "Cycladic culture",
            "descriptionMarkDownFR": "Culture de l'âge du bronze dans les îles de la mer Égée.",
            "descriptionMarkDownEN": "Bronze Age culture in the islands of the Aegean Sea.",
            "dateStart": -3200,
            "dateEnd": -1050,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Semites",
            "labelFR": "Peuples Sémitiques",
            "labelEN": "Semitic peoples",
            "descriptionMarkDownFR": "Groupes ethno-linguistiques du Proche-Orient.",
            "descriptionMarkDownEN": "Ethno-linguistic groups of the Near East.",
            "dateStart": -3800,
            "dateEnd": 2024,
            "availableSnapshots": [-4000, -3000, -2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Afanasevo",
            "labelFR": "Culture d'Afanasievo",
            "labelEN": "Afanasevo culture",
            "descriptionMarkDownFR": "Première culture archéologique indo-européenne de Sibérie du Sud.",
            "descriptionMarkDownEN": "First Indo-European archaeological culture of South Siberia.",
            "dateStart": -3300,
            "dateEnd": -2500,
            "availableSnapshots": [-3000, -2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Yamnaya culture",
            "labelFR": "Culture Yamna",
            "labelEN": "Yamnaya culture",
            "descriptionMarkDownFR": "Culture des steppes pontiques, liée aux Proto-Indo-Européens.",
            "descriptionMarkDownEN": "Pontic steppe culture, linked to Proto-Indo-Europeans.",
            "dateStart": -3300,
            "dateEnd": -2600,
            "availableSnapshots": [-3000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Canaan",
            "labelFR": "Canaan",
            "labelEN": "Canaan",
            "descriptionMarkDownFR": "Région et civilisation du Levant.",
            "descriptionMarkDownEN": "Region and civilization of the Levant.",
            "dateStart": -3500,
            "dateEnd": -1200,
            "availableSnapshots": [-2000],
            "type": "KINGDOM",
            "base64Icon": ""
        },
        {
            "name": "Beaker",
            "labelFR": "Culture Campaniforme",
            "labelEN": "Beaker culture",
            "descriptionMarkDownFR": "Culture dispersée en Europe occidentale (vases en forme de cloche).",
            "descriptionMarkDownEN": "Dispersed culture in Western Europe (bell-shaped beakers).",
            "dateStart": -2800,
            "dateEnd": -1800,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Únětice",
            "labelFR": "Culture d'Unétice",
            "labelEN": "Únětice culture",
            "descriptionMarkDownFR": "Culture de l'âge du bronze ancien en Europe centrale.",
            "descriptionMarkDownEN": "Early Bronze Age culture in Central Europe.",
            "dateStart": -2300,
            "dateEnd": -1600,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Oxus",
            "labelFR": "Civilisation de l'Oxus",
            "labelEN": "Oxus civilization (BMAC)",
            "descriptionMarkDownFR": "Complexe archéologique bactro-margien.",
            "descriptionMarkDownEN": "Bactria–Margiana Archaeological Complex.",
            "dateStart": -2300,
            "dateEnd": -1700,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Xia",
            "labelFR": "Dynastie Xia",
            "labelEN": "Xia Dynasty",
            "descriptionMarkDownFR": "Première dynastie de la Chine traditionnelle.",
            "descriptionMarkDownEN": "First dynasty in traditional Chinese history.",
            "dateStart": -2070,
            "dateEnd": -1600,
            "availableSnapshots": [-2000],
            "type": "EMPIRE",
            "base64Icon": ""
        },
        {
            "name": "Sintashta",
            "labelFR": "Culture de Sintashta",
            "labelEN": "Sintashta culture",
            "descriptionMarkDownFR": "Culture de l'âge du bronze de la steppe eurasienne (invention du char).",
            "descriptionMarkDownEN": "Bronze Age culture of the Eurasian steppe (invention of the chariot).",
            "dateStart": -2100,
            "dateEnd": -1800,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Arctic marine mammal hunters",
            "labelFR": "Chasseurs marins de l'Arctique",
            "labelEN": "Arctic marine mammal hunters",
            "descriptionMarkDownFR": "Cultures spécialisées dans la chasse aux mammifères marins dans le Grand Nord.",
            "descriptionMarkDownEN": "Cultures specialized in hunting marine mammals in the Far North.",
            "dateStart": -4000,
            "dateEnd": 2024,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Chinchorro culture",
            "labelFR": "Culture Chinchorro",
            "labelEN": "Chinchorro culture",
            "descriptionMarkDownFR": "Pêcheurs du désert d'Atacama connus pour leurs momies.",
            "descriptionMarkDownEN": "Fishermen of the Atacama Desert known for their mummies.",
            "dateStart": -7000,
            "dateEnd": -1500,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Mesoamerican hunter-gatherers and maïze farmers",
            "labelFR": "Agriculteurs et chasseurs mésoaméricains",
            "labelEN": "Mesoamerican hunter-gatherers and maize farmers",
            "descriptionMarkDownFR": "Groupes en transition vers l'agriculture du maïs.",
            "descriptionMarkDownEN": "Groups transitioning to maize agriculture.",
            "dateStart": -5000,
            "dateEnd": -1500,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Saharan pastoral nomads",
            "labelFR": "Nomades pastoraux sahariens",
            "labelEN": "Saharan pastoral nomads",
            "descriptionMarkDownFR": "Éleveurs nomades du Sahara lors de sa phase humide.",
            "descriptionMarkDownEN": "Nomadic herders of the Sahara during its wet phase.",
            "dateStart": -6000,
            "dateEnd": -1000,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Australian aboriginal hunter-gatherers",
            "labelFR": "Chasseurs-cueilleurs aborigènes",
            "labelEN": "Australian aboriginal hunter-gatherers",
            "descriptionMarkDownFR": "Peuples autochtones d'Australie.",
            "descriptionMarkDownEN": "Indigenous peoples of Australia.",
            "dateStart": -50000,
            "dateEnd": 2024,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Tasmanian hunter-gatherers",
            "labelFR": "Chasseurs-cueilleurs de Tasmanie",
            "labelEN": "Tasmanian hunter-gatherers",
            "descriptionMarkDownFR": "Peuples isolés de Tasmanie.",
            "descriptionMarkDownEN": "Isolated peoples of Tasmania.",
            "dateStart": -10000,
            "dateEnd": 1876,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Archaic Amerindian hunter-gatherers",
            "labelFR": "Chasseurs-cueilleurs amérindiens archaïques",
            "labelEN": "Archaic Amerindian hunter-gatherers",
            "descriptionMarkDownFR": "Période archaïque des Amériques.",
            "descriptionMarkDownEN": "Archaic period of the Americas.",
            "dateStart": -8000,
            "dateEnd": -1000,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Finno-Ugric taiga hunter-gatherers",
            "labelFR": "Chasseurs de la taïga finno-ougriens",
            "labelEN": "Finno-Ugric taiga hunter-gatherers",
            "descriptionMarkDownFR": "Peuples des forêts boréales parlant des langues ouraliennes.",
            "descriptionMarkDownEN": "Boreal forest peoples speaking Uralic languages.",
            "dateStart": -4000,
            "dateEnd": 1000,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Hittites",
            "labelFR": "Hittites",
            "labelEN": "Hittites",
            "descriptionMarkDownFR": "Empire anatolien puissant de l'âge du bronze.",
            "descriptionMarkDownEN": "Powerful Anatolian Bronze Age empire.",
            "dateStart": -1600,
            "dateEnd": -1178,
            "availableSnapshots": [-2000],
            "type": "EMPIRE",
            "base64Icon": ""
        },
        {
            "name": "Thai",
            "labelFR": "Peuples Taï",
            "labelEN": "Tai peoples",
            "descriptionMarkDownFR": "Anciens groupes ethniques Taï-Kadai.",
            "descriptionMarkDownEN": "Ancient Tai-Kadai ethnic groups.",
            "dateStart": -2000,
            "dateEnd": 2024,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Paleo-Siberian hunter-gatherers",
            "labelFR": "Chasseurs paléo-sibériens",
            "labelEN": "Paleo-Siberian hunter-gatherers",
            "descriptionMarkDownFR": "Anciens peuples de Sibérie orientale.",
            "descriptionMarkDownEN": "Ancient peoples of Eastern Siberia.",
            "dateStart": -15000,
            "dateEnd": 1000,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Andronovo",
            "labelFR": "Culture d'Andronovo",
            "labelEN": "Andronovo culture",
            "descriptionMarkDownFR": "Culture indo-iranienne de l'âge du bronze en Eurasie.",
            "descriptionMarkDownEN": "Indo-Iranian Bronze Age culture in Eurasia.",
            "dateStart": -2000,
            "dateEnd": -900,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Tibeto-Burmanese",
            "labelFR": "Tibéto-Birmans",
            "labelEN": "Tibeto-Burmans",
            "descriptionMarkDownFR": "Locuteurs anciens des langues sino-tibétaines.",
            "descriptionMarkDownEN": "Ancient speakers of Sino-Tibetan languages.",
            "dateStart": -4000,
            "dateEnd": 2024,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Austroasian rice cultures",
            "labelFR": "Cultures rizicoles austroasiatiques",
            "labelEN": "Austroasiatic rice cultures",
            "descriptionMarkDownFR": "Premiers agriculteurs de riz en Asie du Sud-Est.",
            "descriptionMarkDownEN": "Early rice farmers in Southeast Asia.",
            "dateStart": -4000,
            "dateEnd": 2024,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Anatolian tribes",
            "labelFR": "Tribus Anatoliennes",
            "labelEN": "Anatolian tribes",
            "descriptionMarkDownFR": "Peuples divers de l'Asie Mineure.",
            "descriptionMarkDownEN": "Diverse peoples of Asia Minor.",
            "dateStart": -3000,
            "dateEnd": -500,
            "availableSnapshots": [-2000],
            "type": "TRIBE",
            "base64Icon": ""
        },
        {
            "name": "Catacomb culture",
            "labelFR": "Culture des Catacombes",
            "labelEN": "Catacomb culture",
            "descriptionMarkDownFR": "Culture de l'âge du bronze dans la steppe pontique.",
            "descriptionMarkDownEN": "Bronze Age culture in the Pontic steppe.",
            "dateStart": -2800,
            "dateEnd": -2200,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        },
        {
            "name": "Koreans",
            "labelFR": "Coréens (Proto-)",
            "labelEN": "Koreans (Proto-)",
            "descriptionMarkDownFR": "Anciens peuples de la péninsule coréenne (ex: Gojoseon).",
            "descriptionMarkDownEN": "Ancient peoples of the Korean peninsula (e.g., Gojoseon).",
            "dateStart": -2333,
            "dateEnd": 2024,
            "availableSnapshots": [-2000],
            "type": "CULTURE",
            "base64Icon": ""
        }
    ]
};
